<?php
/**
 * File generated by vendor/bin/apigility-upgrade-to-1.5.
 *
 * Original contents are available in config/modules.config.php.old
 */

return [
//     'Zend\\Session',
//     'Zend\\Cache',
//     'Zend\\Db',
//     'Zend\\Filter',
//     'Zend\\Hydrator',
//     'Zend\\InputFilter',
//     'Zend\\I18n',
//     'Zend\\Log',
//     'Zend\\Mvc\\I18n',
//     'Zend\\Paginator',
//     'Zend\\Router',
//     'Zend\\Validator',
//     'ZF\\Apigility',
//     'ZF\\Apigility\\Documentation',
//     'ZF\\ApiProblem',
//     'ZF\\Configuration',
//     'ZF\\OAuth2',
//     'ZF\\MvcAuth',
//     'ZF\\Hal',
//     'ZF\\ContentNegotiation',
//     'ZF\\ContentValidation',
//     'ZF\\Rest',
//     'ZF\\Rpc',
//     'ZF\\Versioning',
//  //   'Zend\Mvc\Console',
    'DoctrineModule',
    'DoctrineORMModule',
//     //'ErrorLogging',
//     'API',
//     'DriverManager',
//     'Authentication',
//     'TacticianModule',
//     'ZfIbmiToolkit',
//     'JsonDbQuery',
];
